# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0002_project_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(to='dragonslayer.Project'),
        ),
    ]
