# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0008_auto_20170909_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='projects',
            field=models.ManyToManyField(to='dragonslayer.Project'),
        ),
    ]
