# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0009_auto_20170909_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='projects',
            field=models.ManyToManyField(related_name='section', to='dragonslayer.Project'),
        ),
    ]
