# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0020_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Sprint'),
        ),
    ]
