# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0022_auto_20170927_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionScreenScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='screen',
            name='issue_types',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='transition',
        ),
        migrations.AddField(
            model_name='issuetype',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Workflow'),
        ),
        migrations.AddField(
            model_name='transition',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Screen'),
        ),
        migrations.AddField(
            model_name='actionscreenscheme',
            name='create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a', to='dragonslayer.Screen'),
        ),
        migrations.AddField(
            model_name='actionscreenscheme',
            name='delete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c', to='dragonslayer.Screen'),
        ),
        migrations.AddField(
            model_name='actionscreenscheme',
            name='edit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='dragonslayer.Screen'),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='action_screen_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.ActionScreenScheme'),
        ),
    ]
