# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0024_auto_20170927_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uid',
        ),
        migrations.AlterField(
            model_name='permission',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
