# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0027_remove_userprofile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='related_issues',
            field=models.ManyToManyField(blank=True, null=True, related_name='_issue_related_issues_+', to='dragonslayer.Issue'),
        ),
    ]
