# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0028_auto_20170927_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
