# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0029_userprofile_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimetype', models.CharField(blank=True, max_length=500, null=True)),
                ('filename', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('filesize', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('actiontype', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('time_Spent', models.TimeField()),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.UserProfile'),
        ),
        migrations.AddField(
            model_name='issue',
            name='current_time_estimate',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='original_time_estimate',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='timespent',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='worklog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.UserProfile'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Issue'),
        ),
        migrations.AddField(
            model_name='issueaction',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.UserProfile'),
        ),
        migrations.AddField(
            model_name='issueaction',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Issue'),
        ),
        migrations.AddField(
            model_name='issueaction',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Screen'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.UserProfile'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Issue'),
        ),
    ]
