# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0030_auto_20170927_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='end_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Status'),
        ),
        migrations.RemoveField(
            model_name='transition',
            name='start_status',
        ),
        migrations.AddField(
            model_name='transition',
            name='start_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='dragonslayer.Status'),
        ),
    ]
