# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0031_auto_20170927_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.ManyToManyField(to='dragonslayer.Permission'),
        ),
    ]
