# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-29 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0035_auto_20170929_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionscreenscheme',
            name='create',
        ),
        migrations.RemoveField(
            model_name='actionscreenscheme',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='actionscreenscheme',
            name='edit',
        ),
        migrations.RemoveField(
            model_name='actionscreenscheme',
            name='org',
        ),
        migrations.RemoveField(
            model_name='actionscreenscheme',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issuetype',
            name='action_screen_scheme',
        ),
        migrations.AddField(
            model_name='issuetype',
            name='create_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a', to='dragonslayer.Screen'),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='delete_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c', to='dragonslayer.Screen'),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='edit_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='dragonslayer.Screen'),
        ),
        migrations.DeleteModel(
            name='ActionScreenScheme',
        ),
    ]
