# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0037_auto_20171005_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Org')),
            ],
        ),
        migrations.RenameModel(
            old_name='Permission',
            new_name='GlobalPermission',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='permissions',
            new_name='global_permissions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_roles',
        ),
        migrations.RemoveField(
            model_name='project_role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='global_permissions',
            field=models.ManyToManyField(to='dragonslayer.GlobalPermission'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='dragonslayer.UserProfile'),
        ),
        migrations.AddField(
            model_name='project_role',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Project'),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuetypes', to='dragonslayer.Project'),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_issuetypes', to='dragonslayer.Workflow'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_prioritys', to='dragonslayer.Project'),
        ),
        migrations.AlterField(
            model_name='status',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='dragonslayer.Column'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='dragonslayer.Workflow'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='dragonslayer.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_permissions',
            field=models.ManyToManyField(to='dragonslayer.ProjectPermission'),
        ),
        migrations.AddField(
            model_name='project_role',
            name='project_permissions',
            field=models.ManyToManyField(to='dragonslayer.ProjectPermission'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project_permissions',
            field=models.ManyToManyField(to='dragonslayer.ProjectPermission'),
        ),
    ]
