# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0038_auto_20171009_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_role',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_roles',
            field=models.ManyToManyField(to='dragonslayer.Project_role'),
        ),
    ]
