# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0039_auto_20171009_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuetype',
            old_name='delete_screen',
            new_name='view_screen',
        ),
        migrations.AlterField(
            model_name='screen',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='dragonslayer.Project'),
        ),
    ]
