# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0041_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Resolution'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
