# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0043_fieldconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfield',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
