# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0044_auto_20171011_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='options',
            field=models.ManyToManyField(to='dragonslayer.Option'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='dragonslayer.Screen'),
        ),
        migrations.AlterField(
            model_name='fieldconfig',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_config', to='dragonslayer.Screen'),
        ),
    ]
