# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 16:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dragonslayer', '0047_auto_20171012_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_type_org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('listener_groups', models.ManyToManyField(to='dragonslayer.Group')),
                ('listeners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Org')),
            ],
        ),
        migrations.CreateModel(
            name='Event_type_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('listener_groups', models.ManyToManyField(to='dragonslayer.Group')),
                ('listeners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Org')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_value', to='dragonslayer.CustomField'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='dragonslayer.Issue'),
        ),
        migrations.AlterField(
            model_name='option',
            name='custom_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dragonslayer.CustomField'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Event_type_org'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Event_type_project'),
        ),
        migrations.AddField(
            model_name='event',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Issue'),
        ),
        migrations.AddField(
            model_name='event',
            name='listener_groups',
            field=models.ManyToManyField(to='dragonslayer.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='listeners',
            field=models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Org'),
        ),
    ]
