# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-21 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0048_auto_20171018_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
