# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0050_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='label',
        ),
        migrations.AddField(
            model_name='issue',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, related_name='issues', to='dragonslayer.Label'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dragonslayer.Sprint'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dragonslayer.Status'),
        ),
    ]
