# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0051_auto_20171023_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldvalue',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
