# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0052_customfieldvalue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldconfig',
            name='comment_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='fix_version_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='fix_version_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='fix_version_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='priority_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='priority_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='priority_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='tasks_visible',
            field=models.BooleanField(default=True),
        ),
    ]
