# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0053_auto_20171025_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldconfig',
            name='epic_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='epic_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='label_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='points_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='points_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fieldconfig',
            name='points_visible',
            field=models.BooleanField(default=True),
        ),
    ]
