# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-26 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0055_auto_20171026_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issue_id_prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
