# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0056_project_issue_id_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='dragonslayer.Project'),
        ),
    ]
