# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0057_auto_20171101_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='due_date',
        ),
        migrations.AddField(
            model_name='issue',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
