# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0058_auto_20171101_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.UserProfile'),
        ),
    ]
