# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-09 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0062_project_board_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('divisions', models.IntegerField(blank=True, null=True)),
                ('layout_type', models.CharField(blank=True, max_length=100, null=True)),
                ('children', models.ManyToManyField(related_name='_layout_children_+', to='dragonslayer.Layout')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Layout')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Status')),
            ],
        ),
    ]
