# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-09 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0064_auto_20171209_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Status'),
        ),
    ]
