# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-09 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0065_auto_20171209_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='_layout_children_+', to='dragonslayer.Layout'),
        ),
    ]
