# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-09 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0066_auto_20171209_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='n',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
