# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-09 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0067_layout_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='parent',
        ),
        migrations.AddField(
            model_name='layout',
            name='root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layout',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
