# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0068_auto_20171209_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='children',
        ),
        migrations.AddField(
            model_name='layout',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Layout'),
        ),
    ]
