# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-10 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0069_auto_20171209_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Col_layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('sections', models.IntegerField()),
                ('layout_type', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Col_layout')),
            ],
        ),
        migrations.AlterField(
            model_name='layout',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dragonslayer.Layout'),
        ),
        migrations.AddField(
            model_name='column',
            name='col_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Col_layout'),
        ),
    ]
