# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-10 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0070_auto_20171210_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='col_layout',
        ),
        migrations.AddField(
            model_name='col_layout',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='col_layout', to='dragonslayer.Column'),
        ),
        migrations.AddField(
            model_name='col_layout',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Status'),
        ),
        migrations.AlterField(
            model_name='col_layout',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dragonslayer.Col_layout'),
        ),
    ]
