# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0071_auto_20171210_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_layout',
            name='width',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
