# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0073_col_layout_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='wid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
