# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0074_column_wid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='wid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
