# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0076_auto_20171220_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='time_ended',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='issue',
            name='time_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
