# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0077_auto_20171220_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='timespent2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
