# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-23 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0079_auto_20171223_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='bg_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
