# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0080_column_bg_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='bg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
