# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-29 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0082_auto_20171226_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
