# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-31 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0083_status_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
