# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-08 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0088_auto_20180108_0013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Password_change_requests',
            new_name='Password_change_request',
        ),
    ]
