# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-09 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0089_auto_20180108_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite_user_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=200)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonslayer.Org')),
            ],
        ),
    ]
