# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-21 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0091_auto_20180112_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='layout',
            field=models.TextField(blank=True, null=True),
        ),
    ]
