# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-23 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0092_column_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sortable_list_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='dragonslayer.Project'),
        ),
    ]
