# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0094_column_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuss', to='dragonslayer.Project'),
        ),
    ]
