# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-05 17:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0095_auto_20180205_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
