# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-06 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0096_auto_20180205_1715'),
    ]


