# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid



def create_uuid(apps, schema_editor):
    Transition = apps.get_model('dragonslayer', 'Transition')
    for t in Transition.objects.all():
        t.uid = uuid.uuid4()
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0097_transition_uid'),
    ]

    operations = [

        migrations.AddField(
            model_name='transition',
            name='uid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='transition',
            name='uid',
            field=models.UUIDField( editable=False, unique=True),
        ),
    ]
