# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0098_auto_20180206_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='column',
        ),
        migrations.AlterField(
            model_name='transition',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
