# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0099_auto_20180206_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='issue_type_icons'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dragonslayer.Project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dragonslayer.Project'),
        ),
    ]
