# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-14 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0100_auto_20180313_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite_user_request',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
