# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-14 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonslayer', '0101_invite_user_request_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bg_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
